version: '3'

services:
  postgresql:
    image: postgres:11.1
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=$DATABASE_PASS
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_DB=$DATABASE_NAME
    volumes:
      - postgresqlData:/var/lib/postgresql/data
    networks:
      - database
    container_name: 'weather-app_posgresql'

  api:
    build:
      context: ./etc/infrastructure/apache2
      dockerfile: apache2.Dockerfile
    image: php7.2.16-apache
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
    networks:
      - database
      - front
    container_name: 'weather-app-api'


volumes:
  postgresqlData:
    driver: local

networks:
  database:
  front: