# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\UserInterface\Web\Controller\:
        resource: '../src/UserInterface/Web/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Queries

    App\Application\Query\GetOneByCityNameQueryHandler:
        public: true
        autowire: true

    # Commands

    App\Domain\Command\GetCurrentWeatherCommandHandler:
        public: true
        arguments:
            - '@GuzzleHttp\Client'
            - '@Symfony\Component\EventDispatcher\EventDispatcher'
            - '%env(OWM_API_KEY)'
            -
    App\Domain\Command\SaveWeatherCommandHandler:
        public: true
        autowire: true

    # Events

    App\Domain\Event\GetCurrentWeatherEventListener:
        tags:
            - { name: kernel.event_listener, event: get.current.weather }

    # Other

    GuzzleHttp\Client:
        class: GuzzleHttp\Client
        public: true

    Symfony\Component\EventDispatcher\EventDispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher
        public: true
        autowire: true

    Ferdyrurka\CommandBus\QueryBusInterface:
        class: Ferdyrurka\CommandBus\QueryBus
        public: true
        autowire: true

    Ferdyrurka\CommandBus\CommandBusInterface:
        class: Ferdyrurka\CommandBus\CommandBus
        public: true
        autowire: true